# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc4b079536b5e2fecc257f4b00e304f947d1993bf9dd90fbef8def635e3925329fcbdaf38c1459310c5ff17ba1eab2c647fd6adb4df104348350af0decd301e

test:
  secret_key_base: 9cefcc001da4dbf0c7b950c24dc6ab44e2a0400153a961bf0dac7da4bad53286a611dba743fe4ae405fb6b136a6a495841d8107b4d7dd29a3a585cc389e9c1fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
